parameters:
    blackoptic_xero.client:  BlackOptic\Bundle\XeroBundle\XeroClient

services:
    blackoptic.xero.client:
        class:        %blackoptic_xero.client%
        arguments:    [%xero_config%]
