parameters:
    blackoptic_xero_client:  BlackOptic\Bundle\XeroBundle\XeroClient

services:
    blackoptic.xero.client:
        class:        %blackoptic_xero_client%
        arguments:    [%xero_config%]
